services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx_proxy
    ports: 
    - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2

  app1:
    build: .
    container_name: app1_instancia

  app2:
    build: .
    container_name: app2_instancia